---
galaxy_info:
  author: FastAPI Base Project Team
  description: Deploy FastAPI Base Project application using Docker Compose
  company: FastAPI Base Project
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - deployment
    - docker
    - application

# dependencies:
#   - role: docker

dependencies: []
