APP:
  NAME: CashLens
  VERSION: 0.1.0
  TIMEZONE: Asia/Ho_Chi_Minh
  API_PREFIX: /api
  MEDIA_URL: /media
  ENABLE_DOCS: true
  PROTECT_MEDIA: true
  CORS_ORIGINS: http://localhost:5173
  TRUSTED_HOST: localhost,127.0.0.1

RATELIMIT:
  REDIS_HOST: redis-cache
  REDIS_PORT: 6379
  REDIS_DB: 3
  LOGIN_RATELIMIT1: 100/5minute
  LOGIN_RATELIMIT2: 1000/hour

TOKEN:
  COOKIE_HTTPONLY: true
  COOKIE_SECURE: true
  COOKIE_SAMESITE: none

POSTGRES:
  HOST: pgbouncer
  PORT: 5432

REDIS_CACHE:
  HOST: redis-cache
  PORT: 6379
  DB: 1
  API_MAX_CONNECTIONS: 20
  WORKER_MAX_CONNECTIONS: 10

REDIS_LOCK:
  HOST: redis-cache
  PORT: 6379
  DB: 2

SENTRY:
  DSN: null
  ENVIRONMENT: development

USER:
  OPEN_REGISTRATION: false

TASKS: {}
