#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
RAW_DIR="$ROOT_DIR/docs/moneylover/private"
SUMMARY_FILE="$ROOT_DIR/docs/moneylover/transaction-capture-summary.json"
SECRET_CONFIG=""
REQUEST_BODY=""

cleanup_capture() {
  [[ -z "$SECRET_CONFIG" ]] || rm -f "$SECRET_CONFIG"
  [[ -z "$REQUEST_BODY" ]] || rm -f "$REQUEST_BODY"
  unset AUTHORIZATION_VALUE COOKIE_VALUE
}
trap cleanup_capture EXIT INT TERM

capture() {
  local endpoint="$1" payload="$2" output="$3" label="$4" status rc
  printf '%s' "$payload" > "$REQUEST_BODY"
  set +e
  status=$(curl --config "$SECRET_CONFIG" \
    --url "https://web.moneylover.me/api/$endpoint" \
    --data-binary "@$REQUEST_BODY" --output "$output" \
    --write-out '%{http_code}')
  rc=$?
  set -e
  if (( rc != 0 )) || [[ ! "$status" =~ ^2 ]]; then
    warn "$label failed (curl=$rc, HTTP=$status); response kept at $output"
    return 1
  fi
  if ! jq -e '.error == 0' "$output" >/dev/null 2>&1; then
    warn "$label returned an unsuccessful or unexpected envelope; response kept at $output"
    return 1
  fi
  printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$label"
  sleep 1
}

banner "Money Lover sanitized API capture"

stage "Revoke the exposed session"
warn "Never reuse the authorization token or cookies pasted into chat or committed in README history."
open_url "https://web.moneylover.me/"
step "Log out of the exposed web session (use log out all devices if Money Lover offers it)."
step "Delete site data/cookies for web.moneylover.me, then sign in again."
if ! confirm "Have you revoked the exposed session and signed in again?"; then
  warn "No requests were sent. Re-run after rotating the session."
  exit 1
fi

stage "Capture fresh credentials in memory"
for command_name in curl jq python3 git; do
  command -v "$command_name" >/dev/null 2>&1 || {
    warn "$command_name is required"
    exit 1
  }
done
step "In DevTools → Network, select a successful Money Lover API request."
step "Copy only the Authorization request-header value (it starts with AuthJWT)."
ask_secret AUTHORIZATION_VALUE "Fresh Authorization value:"
step "Copy only the Cookie request-header value from the same request."
ask_secret COOKIE_VALUE "Fresh Cookie value:"
AUTHORIZATION_VALUE=${AUTHORIZATION_VALUE#authorization: }
AUTHORIZATION_VALUE=${AUTHORIZATION_VALUE#Authorization: }
COOKIE_VALUE=${COOKIE_VALUE#cookie: }
COOKIE_VALUE=${COOKIE_VALUE#Cookie: }
if [[ "$AUTHORIZATION_VALUE" != AuthJWT\ * ]] || [[ -z "$COOKIE_VALUE" ]]; then
  warn "Authorization must start with AuthJWT and Cookie must not be empty."
  exit 1
fi
if [[ "$AUTHORIZATION_VALUE$COOKIE_VALUE" == *[$'\r\n"\\']* ]]; then
  warn "Credentials contain unsupported control/quote characters. Copy header values exactly."
  exit 1
fi

umask 077
mkdir -p "$RAW_DIR"
if ! git -C "$ROOT_DIR" check-ignore -q docs/moneylover/private/; then
  warn "$RAW_DIR is not ignored by Git; refusing to capture private data."
  exit 1
fi
SECRET_CONFIG=$(mktemp)
REQUEST_BODY=$(mktemp)
printf '%s\n' \
  'silent' \
  'show-error' \
  'fail-with-body' \
  'request = "POST"' \
  'connect-timeout = 15' \
  'max-time = 90' \
  'retry = 2' \
  'retry-delay = 2' \
  'header = "accept: application/json"' \
  'header = "content-type: application/json"' \
  'header = "dataformat: json"' \
  'header = "origin: https://web.moneylover.me"' \
  "header = \"authorization: $AUTHORIZATION_VALUE\"" \
  "header = \"cookie: $COOKIE_VALUE\"" > "$SECRET_CONFIG"
unset AUTHORIZATION_VALUE COOKIE_VALUE

stage "Fetch approved probe scopes"
say "Raw responses go only to ignored docs/moneylover/private/. Requests are spaced by one second."
capture "wallet/list" '{}' "$RAW_DIR/list-wallet.json" "wallet list"
mapfile -t WALLET_IDS < <(jq -er '.data | if type == "array" then .[]?._id else error("wallet data is not an array") end' "$RAW_DIR/list-wallet.json")
if (( ${#WALLET_IDS[@]} == 0 )); then
  warn "No wallet IDs were returned; stopping."
  exit 1
fi

RANGE_NAMES=("2026-06" "2026-07" "2026-09-01-to-05")
RANGE_STARTS=("2026-06-01T00:00:00+07:00" "2026-07-01T00:00:00+07:00" "2026-09-01T00:00:00+07:00")
RANGE_ENDS=("2026-06-30T23:59:59+07:00" "2026-07-31T23:59:59+07:00" "2026-09-05T23:59:59+07:00")

for range_index in "${!RANGE_NAMES[@]}"; do
  range_name=${RANGE_NAMES[$range_index]}
  start=${RANGE_STARTS[$range_index]}
  end=${RANGE_ENDS[$range_index]}
  payload=$(jq -cn --arg walletId all --arg startDate "$start" --arg endDate "$end" \
    '{walletId:$walletId,startDate:$startDate,endDate:$endDate}')
  capture "transaction/list" "$payload" "$RAW_DIR/transaction-$range_name-all.json" "$range_name / all wallets"
  for wallet_index in "${!WALLET_IDS[@]}"; do
    wallet_number=$(printf '%02d' "$((wallet_index + 1))")
    payload=$(jq -cn --arg walletId "${WALLET_IDS[$wallet_index]}" --arg startDate "$start" --arg endDate "$end" \
      '{walletId:$walletId,startDate:$startDate,endDate:$endDate}')
    capture "transaction/list" "$payload" \
      "$RAW_DIR/transaction-$range_name-wallet-$wallet_number.json" \
      "$range_name / wallet $wallet_number of ${#WALLET_IDS[@]}"
  done
done

accounts=$(jq -c '[.data[]._id]' "$RAW_DIR/list-wallet.json")
payload=$(jq -cn --argjson accounts "$accounts" '{accounts:$accounts}')
capture "transaction/debts" "$payload" "$RAW_DIR/list-debts.json" "debts / all wallets"

stage "Create sanitized comparison summary"
python3 - "$RAW_DIR" "$SUMMARY_FILE" <<'PY'
import json
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

raw = Path(sys.argv[1])
summary_path = Path(sys.argv[2])
wallet_payload = json.loads((raw / "list-wallet.json").read_text())
wallets = wallet_payload["data"]
wallet_labels = {wallet["_id"]: f"wallet_{index:02d}" for index, wallet in enumerate(wallets, 1)}


def rows(path: Path, nested: bool = True) -> list[dict]:
    payload = json.loads(path.read_text())
    data = payload["data"]
    return data["transactions"] if nested else data


def summarize(items: list[dict]) -> dict:
    ids = [item.get("_id") for item in items if item.get("_id")]
    dates = [item.get("displayDate") for item in items if item.get("displayDate")]
    by_wallet = Counter(
        wallet_labels.get(item.get("account", {}).get("_id"), "unknown_wallet") for item in items
    )
    return {
        "count": len(items),
        "records_with_id": len(ids),
        "unique_id_count": len(set(ids)),
        "duplicate_id_count": len(ids) - len(set(ids)),
        "min_display_date": min(dates, default=None),
        "max_display_date": max(dates, default=None),
        "count_by_wallet": dict(sorted(by_wallet.items())),
    }

ranges = ["2026-06", "2026-07", "2026-09-01-to-05"]
result = {
    "generated_at": datetime.now(timezone.utc).isoformat(),
    "evidence_level": "sanitized summary of owner-authorized private API captures",
    "wallet_count": len(wallets),
    "ranges": {},
}
for range_name in ranges:
    all_rows = rows(raw / f"transaction-{range_name}-all.json")
    all_ids = {item.get("_id") for item in all_rows if item.get("_id")}
    union_ids: set[str] = set()
    per_wallet = {}
    for index, wallet in enumerate(wallets, 1):
        wallet_rows = rows(raw / f"transaction-{range_name}-wallet-{index:02d}.json")
        wallet_ids = {item.get("_id") for item in wallet_rows if item.get("_id")}
        union_ids.update(wallet_ids)
        expected_id = wallet["_id"]
        item_summary = summarize(wallet_rows)
        item_summary["unexpected_wallet_count"] = sum(
            item.get("account", {}).get("_id") != expected_id for item in wallet_rows
        )
        per_wallet[f"wallet_{index:02d}"] = item_summary
    result["ranges"][range_name] = {
        "all": summarize(all_rows),
        "per_wallet": per_wallet,
        "per_wallet_union_unique_id_count": len(union_ids),
        "all_equals_per_wallet_union": all_ids == union_ids,
        "missing_from_all_count": len(union_ids - all_ids),
        "extra_in_all_count": len(all_ids - union_ids),
    }

debt_rows = rows(raw / "list-debts.json", nested=False)
result["debts"] = summarize(debt_rows)
summary_path.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n")
PY
chmod 600 "$SUMMARY_FILE"

if grep -RIlE 'authorization:|AuthJWT|cf_clearance=' "$SUMMARY_FILE" >/dev/null; then
  warn "Secret-like text reached the summary; deleting it and stopping."
  rm -f "$SUMMARY_FILE"
  exit 1
fi
say "Raw private captures: $RAW_DIR (Git-ignored)"
say "Sanitized summary: $SUMMARY_FILE"
note "Review the summary before committing it. Delete raw captures when investigation is complete."

finish
