# .github/workflows/ansible-lint.yml
name: ansible-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
      - develop

  pull_request:
    branches: ['main', 'develop', 'stable', 'release/v*']

jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        # optional (see below):
        with:
          args: ''
          setup_python: 'true'
          working_directory: ''
          requirements_file: ''
